### ISSUE TITLE
Missing settings

### ISSUE THREAD

**Issue by vinitkumar** [pdvyas/thumbserv#1]
I think you missed out. The app is not complete as the settings directory is missing.

``` js
module.js:340
    throw err;
          ^
Error: Cannot find module '../settings'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/vinitkumar/thumbserv/routes/serveImage.js:6:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by pdvyas** [comment]
That's supposed to be secret :) I think it's suppose to have aws keys.

**Comment by vinitkumar** [comment]
Okay, but the better way is to the keep the file and use the aws credentials as environment variables.

**Comment by pdvyas** [comment]
is this still in production somewhere?
It should not be!

**Comment by vinitkumar** [comment]
Nope!
